environments:
  contacts-ui-docker:
    pipelines:
      - frontend-package

pipelines:
  frontend-compile:
    group: contacts-app
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/shivanir12/contacts-ui.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: bash
                   arguments:
                     - "-c"
                     - "yarn install --production && yarn build"
              artifacts:
                - build:
                    source: build
              resources:
                - yarn
  frontend-package:
    group: contacts-app
    materials:
      compilation:
        pipeline: frontend-compile
        stage: build
      mygit:
        git: https://github.com/shivanir12/contacts-ui.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - fetch:
                   pipeline: frontend-compile
                   stage: build
                   job: build
                   source: build
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "docker build -t contacts-ui:${GO_PIPELINE_LABEL} -f Dockerfile.build ."
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "echo contacts-ui:${GO_PIPELINE_LABEL} > contacts-ui-version.txt"
              artifacts:
                - build:
                    source: contacts-ui-version.txt
              resources:
                - docker
      - publish:
          jobs:
            publish:
              tasks:
                - fetch:
                   stage: build
                   job: build
                   is_file: yes
                   source: contacts-ui-version.txt
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASSWORD}"
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "docker tag `cat contacts-ui-version.txt` ${DOCKERHUB_USER}/`cat contacts-ui-version.txt`"
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "docker push ${DOCKERHUB_USER}/`cat contacts-ui-version.txt`"
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "echo ${DOCKERHUB_USER}/`cat contacts-ui-version.txt` > contacts-ui-image-version.txt"
              artifacts:
                - build:
                    source: contacts-ui-image-version.txt
              resources:
                - docker
